ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/fw_inc
ccflags-y += -I$(srctree)/techpack/ais/drivers
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_smmu/

obj-$(CONFIG_MSM_AIS) += icp_hw/
obj-$(CONFIG_MSM_AIS) += cam_icp_subdev.o cam_icp_context.o hfi.o
