ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/cpas_top
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/camss_top

obj-$(CONFIG_MSM_AIS) += cpas_top/
obj-$(CONFIG_MSM_AIS) += camss_top/
obj-$(CONFIG_MSM_AIS) += cam_cpas_soc.o cam_cpas_intf.o cam_cpas_hw.o