ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_smmu/
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_cci

obj-$(CONFIG_MSM_AIS) += cam_cci_dev.o cam_cci_core.o cam_cci_soc.o
