ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas

obj-$(CONFIG_MSM_AIS) += cam_camsstop_hw.o
