ccflags-y += -I$(srctree)/techpack/ais/drivers
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_hyp_intf
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
obj-$(CONFIG_MSM_AIS_HYP) += cam_hyp_intf.o
