ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_smmu/
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils

obj-$(CONFIG_MSM_AIS) += cam_sensor_dev.o cam_sensor_core.o cam_sensor_soc.o
