ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/ipe_hw
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/fw_inc
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include

obj-$(CONFIG_MSM_AIS) += ipe_dev.o ipe_core.o ipe_soc.o
