# SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note

# Legacy file used for kernel 4.19.x build system to install
# UAPI headers.

header-y += media/cam_cpas.h
header-y += media/cam_defs.h
header-y += media/cam_fd.h
header-y += media/cam_icp.h
header-y += media/cam_isp.h
header-y += media/cam_isp_vfe.h
header-y += media/cam_isp_ife.h
header-y += media/cam_jpeg.h
header-y += media/cam_req_mgr.h
header-y += media/cam_sensor.h
header-y += media/cam_sync.h
header-y += media/ais_isp.h
header-y += media/ais_sensor.h

#header-y += camera/media/msm_vidc.h
#header-y += camera/media/msm_sde_rotator.h
#header-y += camera/media/cam_lrme.h
#header-y += camera/media/cam_hyp_intf.h
header-y += media/msm_cam_sensor.h
header-y += media/msm_camera.h
header-y += media/msm_isp.h

#header-y += camera/media/msmb_camera.h
#header-y += camera/media/msmb_generic_buf_mgr.h
#header-y += camera/media/msmb_isp.h
#header-y += camera/media/msmb_ispif.h
#header-y += camera/media/msmb_pproc.h

# for compile temp add it
#header-y += media/msm_media_info.h

