ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include

obj-$(CONFIG_MSM_AIS) += icp_hw_mgr/ a5_hw/ ipe_hw/ bps_hw/
