ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/ais/drivers/cam_utils

obj-$(CONFIG_MSM_AIS_SENSOR_SERDES) += cam_sensor_serdes_dev.o
