obj-$(CONFIG_MSM_AIS) += cam_req_mgr/
#obj-$(CONFIG_MSM_AIS) += cam_hyp_intf/
obj-$(CONFIG_MSM_AIS_UTIL) += cam_utils/
obj-$(CONFIG_MSM_AIS) += cam_core/
obj-$(CONFIG_MSM_AIS) += cam_sync/
obj-$(CONFIG_MSM_AIS) += cam_smmu/
obj-$(CONFIG_MSM_AIS) += cam_cpas/
obj-$(CONFIG_MSM_AIS) += cam_cdm/
obj-$(CONFIG_MSM_AIS) += ais_isp/
obj-$(CONFIG_MSM_AIS) += cam_isp/
obj-$(CONFIG_MSM_AIS) += cam_sensor_module/
obj-$(CONFIG_MSM_AIS) += cam_icp/
obj-$(CONFIG_MSM_AIS) += cam_jpeg/
obj-$(CONFIG_MSM_AIS) += cam_fd/
obj-$(CONFIG_MSM_AIS) += cam_lrme/
obj-$(CONFIG_V4L2_LOOPBACK_V2) += v4l2loopback-master_v2/


