# SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note

# Legacy file used for kernel 4.19.x build system to install
# UAPI headers.

header-y += cam_cpas.h
header-y += cam_defs.h
header-y += cam_fd.h
header-y += cam_icp.h
header-y += cam_isp.h
header-y += cam_isp_vfe.h
header-y += cam_isp_ife.h
header-y += cam_jpeg.h
header-y += cam_req_mgr.h
header-y += cam_sensor.h
header-y += cam_sync.h
header-y += ais_isp.h
header-y += ais_sensor.h

header-$(CONFIG_V4L2_LOOPBACK_V2) += ais_v4l2loopback.h

# for compile temp add it
header-y += msm_media_info.h
